  spring:
    datasource:
      hikari:
        maximum-pool-size: 4
      url: jdbc:postgresql://3.38.102.66:5432/ijs_server
      username: ijs_user
      password: mega123!@#
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          enable_lazy_load_no_trans: true